django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("users/", include("accounts.urls")),
    path("players/", include("players.urls")),
    path("teams/", include("teams.urls")),
    path("news/", include("news.urls")),
    path("logs/", include("logs.urls")),
    path("stafftools/", include("stafftools.urls")),
    path("stats/", include("stats.urls")),
    path("events/", include("events.urls")),
    path("", include("pages.urls")),
    
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

logs/urls.py
# Django imports
from django.urls import path

# Local imports
from players import views
from logs import views

# Create your urls here.
urlpatterns = [
    path("log/upgrade/<int:id>/", views.upgrade_log, name="upgrade_log"),
    path("log/payment/<int:id>/", views.payment_log, name="payment_log"),
    path("log/<int:id>/", views.view_logs, name="view_logs"),
    path("upgrades/incomplete/", views.IncompleteLogs.as_view(), name="incomplete_logs"),
    path("upgrade/<int:id>/complete/", views.mark_upgrade_complete, name="mark_upgrade_complete"),
    path("upgrades/incomplete/download/", views.download_incomplete_logs, name="download_incomplete_logs"),
]

teams/urls.py
# Django imports
from django.urls import path

# Local imports
from teams import views

# Create your urls here.
urlpatterns = [
    path("list/", views.team_list, name="team_list"),
    path("team/<int:id>/", views.team_page, name="team_page"),
    path("drafts/list/", views.draft_list, name="draft_list"),
    path("draft/<int:id>/", views.draft_page, name="draft_page"),
    path("team/roster/move/<int:id>/", views.RosterMoveView.as_view(), name="roster_move"),
]

teams/models.py
# Python imports

# Django imports
from django.db import models

# Local imports
from simulation.scripts import default as default
from players.models import Player
from accounts.models import CustomUser

# Create your models here.
class Team(models.Model):

    # Defined fields
    manager = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=32)
    city = models.CharField(max_length=32)
    color = models.CharField(max_length=10, default="#434648")
    surge = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.city} {self.name}"

class TeamLogs(models.Model):

    # Defined fields (positions)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    # Defined fields (positions, playtypes, focus, & sliders)
    playbook = models.CharField(max_length=32, default="Team Playbook 1")
    offensive_focus = models.CharField(max_length=32, default="No Preference")
    offensive_tempo = models.CharField(max_length=32, default="No Preference")
    offensive_rebounding = models.CharField(max_length=32, default="No Preference")
    defensive_focus = models.CharField(max_length=32, default="No Preference")
    defensive_aggression = models.CharField(max_length=32, default="No Preference")
    defensive_rebounding = models.CharField(max_length=32, default="No Preference")
    run_plays = models.IntegerField(default=50)
    zone_usage = models.IntegerField(default=50)

    # Defined fields (position lineups, play initiators, playtypes, & touches)
    lineup = models.JSONField(default=default.default_lineup)


class Draft(models.Model):

    # Defined fields
    season = models.IntegerField(unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Draft for Season {self.season}"
    
class DraftPick(models.Model):

    # Defined fields
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    draft = models.ForeignKey(Draft, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    round = models.IntegerField()
    pick = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.team} Round {self.round} Pick {self.pick} Player {self.player}"
    
class DraftOrder(models.Model):

    # Defined fields
    draft = models.ForeignKey(Draft, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    order = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.team} Order {self.order}"

teams/views.py
# Python imports

# Django imports
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View


# Local imports
from teams.models import Team, Draft, DraftPick, DraftOrder
import simulation.payment as payment
import simulation.statfinder as statfinder
import simulation.config as config

# Create your views here.
def team_page(request, id):
    # Initialize variables
    team = Team.objects.get(pk=id)
    salary_book = payment.get_salary_book(team)
    current_week = config.CONFIG_SEASON["CURRENT_WEEK"]
    # Get the players' averages & totals
    stat_finder = statfinder.StatFinder()
    team_stats = stat_finder.team_player_stats(team)
    # Loop through the players
    return render(request, "teams/team_page.html", {
        "team": team, 
        "current_week": current_week, 
        "salary_book": salary_book, 
        "team_stats": team_stats, 
        "rookie_cap_hit": config.CONFIG_PLAYER["ROOKIE_CAP_HIT"]
    })

def team_list(request):
    teams = Team.objects.all()
    return render(request, "teams/team_list.html", {"teams": teams})

def draft_page(request, id):
    draft = Draft.objects.get(pk=id)
    draft_order = DraftOrder.objects.filter(draft=draft).order_by("order")
    return render(request, "teams/draft_page.html", {"draft": draft, "draft_order": draft_order})

def draft_list(request):
    return HttpResponse("Work in progress...")

class RosterMoveView(View):

    def get(self, request, id):
        team = Team.objects.get(pk=id)
        if team.manager == request.user:
            return render(request, "teams/roster_move.html")

    def post(self, request):
        return HttpResponse("POST request")

templates/teams/draft_page.html
{% extends '_base.html' %}

{% load static %}

{% block title %}Draft Page{% endblock %}

{% block content %}
    <div class="container-fluid p-4">
        <h1>Draft Page</h1>
        <p class="fw-bold">Draft for <span class="text-warning">Season {{ draft.season }}</span></p>
        <hr>
        <div class="row">
            <!-- Draft results table -->
            <div class="col-md-6">
                <h2>Draft Results</h2>
                <div id="draft-results-table">
                    <div class="table-responsive">
                        <table class="table table-dark table-striped">
                            <thead>
                                <tr>
                                    <th>Pick</th>
                                    <th>Team</th>
                                    <th>Player</th>
                                    <th>Position</th>
                                    <th>Height</th>
                                    <th>Weight</th>
                                    <th>Wingspan</th>
                                </tr>
                            </thead>
                            <tbody class="table table-dark table-hover">
                                {% for draft_pick in draft.draftpick_set.all %}
                                    <tr>
                                        <td>R{{ draft_pick.round }} - P{{ draft_pick.pick }}</td>
                                        <td>{{ draft_pick.team.name }}</td>
                                        <td>{{ draft_pick.player.first_name }} {{ draft_pick.player.last_name }}</td>
                                        <td>{{ draft_pick.player.position }}</td>
                                        <td>{{ draft_pick.player.height_imperial }}</td>
                                        <td>{{ draft_pick.player.weight }}lbs</td>
                                        <td>{{ draft_pick.player.wingspan }}/100</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>            
            </div>
            <!-- Draft order table -->
            <div class="col-md-6">
                <h2>Draft Order</h2>
                <div id="draft-order-table">
                    <div class="table-responsive">
                        <table class="table table-dark table-striped">
                            <thead>
                                <tr>
                                    <th>Order</th>
                                    <th>Team</th>
                                </tr>
                            </thead>
                            <tbody class="table table-dark table-hover">
                                {% for order in draft_order %}
                                    <tr>
                                        <td>{{ order.order }}</td>
                                        <td><a href="{% url 'team_page' order.team.id %}" class="text-decoration-none">{{ order.team.city }} {{ order.team.name }}</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/teams/roster_move.html
{% extends '_base.html' %}
{% load style_filters %}

{% block title %}Roster Move{% endblock %}


{% block content %}
<div class="container-fluid p-md-5">
    <h1>Roster Move</h1>
    <form>
        {% csrf_token %}
    </form>
</div>
{% endblock %}

templates/teams/team_list.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Players{% endblock %}

{% block styles %}
<style>
    input::placeholder {
        color: gray!important;
    }
</style>
{% endblock %}

{% block content %}
<div class="container-fluid p-md-5">
    <h1>Team List</h1>
    <form>
        {% csrf_token %}
        <span class="counter pull-right"></span>
        <div id="search-table">
            <div class="table-responsive">
                <table class="table table-dark table-striped">
                    <thead>
                        <tr>
                            <th><i class="fas fa-user"></i> Team</th>
                            <th><i class="fas fa-star"></i> Manager</th>
                        </tr>
                    </thead>
                    <tbody class="table table-dark table-hover">
                        {% for team in teams %}
                            <tr>
                                <td><a href="{% url 'team_page' team.id %}">{{ team.city }} {{ team.name }}</a></td>
                                <td><a href="{% url 'user' team.manager.id %}">{{ team.manager }}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </div>
            </div>            
        </div>
    </form>
</div>

{% endblock %}

{% block scripts %}
{% endblock %}